#!/usr/bin/env bash
# Comment: Bash script that will display information about subdomains
# shellcheck disable=SC2086
func()
{
    if [ "$#" -eq 2 ]
    then
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -v var="$2" 'NR==2{print "The subdomain " var " is a " $4 " record and points to " $5}'
    else
	for sub in "www" "lb-01" "web-01" "web-02"
	do
	    dig "$sub.$1" | grep -A1 'ANSWER SECTION:' | awk -v var="$sub" 'NR==2{ print "The subdomain " var " is a " $4 " record and points to " $5}'
	done
    fi
}

func $1 $2
