#!/usr/bin/env bash
# comment: current task install nginx in a server
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
