#!/usr/bin/env bash
# Comment: Current task 404 error message custom
sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
sudo sed -i "30i \\\trewrite ^/redirect_me https://https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404_error.html
sudo sed -i "30i \\\terror_page 404 /404_error.html;\n\tlocation = /404_error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default
sudo service nginx restart
