#!/usr/bin/env bash
# Comment: Current task configures header on current location
sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
sudo sed -i "51i \\\t\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
