#!/usr/bin/env bash
# Comment: run command as a super user change permissions on nginx.conf
sudo pkill -9 apache2
chown -R nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx bash -c 'service nginx restart'
